#ifndef __SED_TOOLS_COLUMNS_H__
#define __SED_TOOLS_COLUMNS_H__

#define COLUMN_VALUES 0x01
#define COLUMN_ENABLED 0x05
#define COLUMN_DONE	0x02
#define COLUMN_STARTCOL 0x03
#define COLUMN_ENDCOL   0x04
#define COLUMN_PIN  0x03
#define COLUMN_LIFECYCLE 0x06
#define COLUMN_WHERE    0x00
#define COLUMN_ACTIVEKEY 0x0A
#define COLUMN_TRYLIMIT 0x05
#define COLUMN_TRIES 0x06
#define COLUMN_PERSISTENCE 0x07

#define ROW_STARTROW    0x01
#define ROW_ENDROW      0x02

#define NAME_BOOLEANEXPR    0x03
#define NAME_ENABLE         0x01
#define NAME_DONE           0x02
#define NAME_HOSTCHALLENGE          0
#define NAME_HOSTSIGNINGAUTHORITY   3
#define NAME_HOSTPROPERTIES         0

#define NAME_VALUES 1
#define NAME_RANGESTART 3
#define NAME_RANGELENGTH 4
#define NAME_READLOCKENABLED 5
#define NAME_WRITELOCKENABLED 6
#define NAME_READLOCKED 7
#define NAME_WRITELOCKED 8
#define NAME_ACTIVEKEY 0xA
#define NAME_STARTCOLUMN 3
#define NAME_ENDCOLUMN 4
#endif /* __SED_TOOLS_UIDS_H__ */
